# Site settings
title: OdontoSP | Estética y salud dental
description: "A responsive Jekyll theme for dental clinics."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Odonto SP
    hero_description: Estética y salud dental

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 4522-8197
    emergency: 15 2237-4895
    email: odontospestetica@gmail.com
    address: Viamonte 2188 <br> CABA - Buenos Aires <br> Argentina




# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Viamonte 2188, CABA, Buenos Aires, Argentina
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com/odontospestetica/
instagram: http://instagram.com/odontosp/
feed: no

# Footer
copyright: © 2017 OdontoSP - Todos los derechos reservados

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
