# Site settings
title: OdontoSP | Estética y salud dental
description: "El especialista en estética dental."
baseurl: "" # the subpath of your site, e.g. /blog
url: "odontosp.com.ar" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Odonto SP
    hero_description: Somos especialistas en diseño de sonrisas y estética dental.

# Contact form
api_token: d1328929419a4306133901aeb09bed4c # Enter API token here

# Contact info
contact:
    phone: 4522-8197
    emergency: +54 9 11 2237-4895
    email: odontospestetica@gmail.com
    address: Larrea 1273 <br> CABA - Buenos Aires <br> Argentina

dias_atencion: Miércoles, Viernes y Sábados de 14:00 a 18:30 hs

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Larrea 1273, CABA, Buenos Aires, Argentina
    address_details: svg/min/logo.svg

# Social settings
instagram: http://instagram.com/odontosp/
facebook: http://facebook.com/odontospestetica/

# Footer
copyright: © 2017 OdontoSP - Todos los derechos reservados

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: UA-104947173-1
google_verification:
